### ISSUE TITLE
Rotating record in record player

### ISSUE THREAD

**Issue by Gamerbolts** [Stumblinbear/BetterRecords#30]
Hi, I am creating a modpack and on single player placing the record in the player works fine you place it in close it and it animates properly. However on my server which is running Kcauldron placing the record in the player the record item is shown spinning around out of the player. Any help is appreciated. Thank you

**Comment by NicholasFeldman** [comment]
Please provide some more information.

What version of the mod are you running?

**Comment by Gamerbolts** [comment]
1.7.10 version 1.2.1 I do think it may be Kcauldron but have no idea if there is a setting I can change to solve it.

**Comment by NicholasFeldman** [comment]
Unfortunately, we are no longer supporting 1.7.10. This issue has also never come up before, which I'm going to say is probably also caused by Kcauldron, which we also don't support. We only ensure compatibility with official Forge builds, and if compatibility breaks with other server software that's on them.
