### ISSUE TITLE
Adding Features

### ISSUE THREAD

**Issue by Sang-bin** [Stumblinbear/BetterRecords#36]
I will suggest additional features as a personal wish

1. I want to be able to adjust the music volume with the game volume system. It mixes with the music of the game.
2. I want to be able to open the player even if I have a disc or anything.
3. If the download fails, I'd like to stop and try again. It takes too long to restart the minecraft.
4. Adding a portable player is fantastic.

Your mod is really useful. Thank you for making.

**Comment by NicholasFeldman** [comment]
New features/changes are being held off on until the kotlin migration is finished, except for major bugs.

These suggestions will be taken into account though.

1. This will likely get tweaked when #28 is closed.

2. I'll make a note to look over the logic for this, and possibly tweak it.

3. Possibly related to #32. This will be fixed when that issue is closed.

4. This will be considered

**Comment by NicholasFeldman** [comment]
Everything here has been covered in separate issues, no immediate action needed so I'm closing this.
