### ISSUE TITLE
Limiting speakers radius

### ISSUE THREAD

**Issue by prodkid** [Stumblinbear/BetterRecords#5]
Is there a current way to limit how far music can be played?

**Comment by AngrySoundTech** [comment]
The current functionality is that a record player will have a default radius of 40 blocks, with the ability to increase this radius by connecting speakers.

This being said, there is no way to limit the radius, only to increase it.

**Comment by Borlea** [comment]
Could possibly add a max in the config..

**Comment by prodkid** [comment]
What @Borlea  suggested would be very helpful for server owners. Would be nice to limit how much a player can have their music to be played out and not engulf the entire server with random music.

**Comment by AngrySoundTech** [comment]
Thank you for explaining the reasoning. I see what you mean, and why this would be very helpful.

I think it would be best to add the config value with a default value of -1 (infinite), so that current functionality is not impacted, but the option would then be there for those who wish to use it.

Additionally, this involves configuration options for the server, currently which there are none.
