### ISSUE TITLE
Lazers and Strobes flash super quick with Thermos server build 58 forge 1614

### ISSUE THREAD

**Issue by InuYasha86000** [Stumblinbear/BetterRecords#7]
I have recently updated my modded server to the latest build of Thermos build 58 forge 1614 and I also added in LookingGlass to see if that mod worked finally, it did, but I noticed some strange things with BetterRecords mod.
the lazers and strobes flashed really quick no matter what flash setting they were on, and I also noticed the disc in the record player rotated really quick as well.
i'm not sure if it's a lookingglass compatibility issue or a thermos update issue as I have only just noticed this issue today.

**Comment by AngrySoundTech** [comment]
From what I understand, Thermos build 58 is for minecraft 1.7.10. Unfortunately, I'm not continuing to work on updates for old versions of minecraft, unless it's a major bug that needs addressing. 

Since this also seems to be an issue with LookingGlass, there is most likely little that could be done on our side as well. Perhaps @XCompWiz could weigh in on if this is a known problem with other mods as well.

**Comment by InuYasha86000** [comment]
Yes it's for 1.7.10, I forgot to mention that, and i'll check to see if eliminating lookingglass fixes the quick lazer, strobe, and rotating disc issue.
